// Demo data for guest users to explore the app

export const demoCompanyObjectives = [
  {
    id: 'demo-obj-1',
    title: 'Increase Monthly Active Users',
    description: 'Grow our user base through product improvements and marketing',
    icon: '📈',
    metric_name: 'MAU',
    metric_current: 12500,
    metric_target: 20000,
    goal_type: 'company' as const,
    year: new Date().getFullYear(),
    quarter: Math.ceil((new Date().getMonth() + 1) / 3) as 1 | 2 | 3 | 4,
    created_at: new Date().toISOString(),
    updates: [],
  },
  {
    id: 'demo-obj-2',
    title: 'Improve Customer Satisfaction',
    description: 'Deliver exceptional customer experience across all touchpoints',
    icon: '⭐',
    metric_name: 'NPS Score',
    metric_current: 42,
    metric_target: 60,
    goal_type: 'company' as const,
    year: new Date().getFullYear(),
    quarter: Math.ceil((new Date().getMonth() + 1) / 3) as 1 | 2 | 3 | 4,
    created_at: new Date().toISOString(),
    updates: [],
  },
  {
    id: 'demo-obj-3',
    title: 'Ship v2.0 Platform',
    description: 'Complete the next major version of our platform',
    icon: '🚀',
    metric_name: 'Features Shipped',
    metric_current: 8,
    metric_target: 12,
    goal_type: 'company' as const,
    year: new Date().getFullYear(),
    quarter: Math.ceil((new Date().getMonth() + 1) / 3) as 1 | 2 | 3 | 4,
    created_at: new Date().toISOString(),
    updates: [],
  },
]

export const demoTeamGoals = [
  {
    id: 'demo-goal-1',
    title: 'Launch referral program',
    description: 'Build and ship a viral referral system',
    icon: '🎁',
    metric_name: 'Referrals',
    metric_current: 340,
    metric_target: 500,
    goal_type: 'team' as const,
    parent_goal_id: 'demo-obj-1',
    year: new Date().getFullYear(),
    quarter: Math.ceil((new Date().getMonth() + 1) / 3) as 1 | 2 | 3 | 4,
    created_at: new Date().toISOString(),
    updates: [
      {
        id: 'demo-update-1',
        goal_id: 'demo-goal-1',
        notes: 'Launched beta version to 100 users, seeing good initial traction!',
        metric_value: 340,
        created_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
      },
    ],
  },
  {
    id: 'demo-goal-2',
    title: 'Reduce response time',
    description: 'Improve support response speed',
    icon: '⚡',
    metric_name: 'Avg Hours',
    metric_current: 4,
    metric_target: 2,
    goal_type: 'individual' as const,
    parent_goal_id: 'demo-obj-2',
    year: new Date().getFullYear(),
    quarter: Math.ceil((new Date().getMonth() + 1) / 3) as 1 | 2 | 3 | 4,
    created_at: new Date().toISOString(),
    updates: [
      {
        id: 'demo-update-2',
        goal_id: 'demo-goal-2',
        notes: 'Implemented new triage system, seeing improvements already',
        metric_value: 4,
        created_at: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
      },
    ],
  },
  {
    id: 'demo-goal-3',
    title: 'Complete dashboard redesign',
    description: 'Ship the new analytics dashboard',
    icon: '🎨',
    metric_name: '% Complete',
    metric_current: 75,
    metric_target: 100,
    goal_type: 'team' as const,
    parent_goal_id: 'demo-obj-3',
    year: new Date().getFullYear(),
    quarter: Math.ceil((new Date().getMonth() + 1) / 3) as 1 | 2 | 3 | 4,
    created_at: new Date().toISOString(),
    updates: [
      {
        id: 'demo-update-3',
        goal_id: 'demo-goal-3',
        notes: 'Finalized designs, dev work 75% complete. On track for next week!',
        metric_value: 75,
        created_at: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
      },
    ],
  },
]

export const demoOrgSettings = {
  fiscal_year_start_month: 1,
  checkin_cadence_days: 7,
}
